### ISSUE TITLE
SBV import ignoring new lines in captions

### ISSUE THREAD

**Issue by ajayyy** [YouCap/YouCap-Website#12]
The JSON file preserves them fine, and it does export properly

**Comment by JamesEConnor** [comment]
Can you give an example of a video that this is occurring on to facilitate replication of the bug?

**Comment by ajayyy** [comment]
[captions.zip](https://github.com/YouCap/YouCap-Website/files/5613634/captions.zip)

**Comment by JamesEConnor** [comment]
Didn't mean to close the issue, but can you confirm it's resolved by the fix?

**Comment by ajayyy** [comment]
No, this did not fix it
