### ISSUE TITLE
[Bug] 500/403 Error with Second Google Account

### ISSUE THREAD

**Issue by JamesEConnor** [YouCap/YouCap-Website#16]
Creating captions with one Google account and then reviewing with another causes a 500/403 error. This likely has to do with session storage of CSRF tokens, as sessions aren't destroyed between Google sign outs.

Potential fix:
Store the Google account token as a session cookie and compare it to any submitted Google account token. If they don't match, destroy the session and start a new one.

**Comment by JamesEConnor** [comment]
This issue may have been unrelated to the second Google account. Can you confirm whether it still exists or if it's been resolved?

**Comment by ajayyy** [comment]
Seems fixed

**Comment by JamesEConnor** [comment]
Awesome, sounds good.
